const WA = "8801604985164";
// Optional server-side WhatsApp Cloud API relay. Keep tokens on the server, never in this file.
const WA_API_ENDPOINT = "/api/whatsapp/order";
const social = {facebook:"https://www.facebook.com/share/1FCKwXKCGo/",instagram:"https://www.instagram.com/grozofficial?stkn=bzB4NHc2YzhkZnEx"};
const paymentNumbers = {bKash:"01604985164",Nagad:"01814026318",Upay:"01814026318",Rocket:"01604985164"};

document.addEventListener("DOMContentLoaded",()=>{
 document.querySelectorAll(".menu").forEach(btn=>btn.addEventListener("click",()=>document.querySelector(".navlinks")?.classList.toggle("open")));
 const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add("show")),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
 document.querySelectorAll("[data-social]").forEach(a=>{const key=a.dataset.social;if(social[key])a.href=social[key]});
 document.querySelectorAll("[data-copy]").forEach(btn=>btn.addEventListener("click",()=>copyText(btn.dataset.copy)));
 initSlider(); initCheckout(); initPayment(); initCart(); initCartCount();
});
function copyText(value){navigator.clipboard?.writeText(value).then(()=>toast((typeof currentLang!=="undefined"&&currentLang==="bn")?"নম্বর কপি হয়েছে":"Number copied"));}
function toast(message){let t=document.querySelector(".toast");if(!t){t=document.createElement("div");t.className="toast";document.body.appendChild(t)}t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function initSlider(){const slides=[...document.querySelectorAll(".slide")],dots=[...document.querySelectorAll(".slider-dot")];if(!slides.length)return;let index=0,timer;const show=i=>{index=i;slides.forEach((s,n)=>s.classList.toggle("active",n===i));dots.forEach((d,n)=>d.classList.toggle("active",n===i))};const start=()=>{clearInterval(timer);timer=setInterval(()=>show((index+1)%slides.length),5000)};dots.forEach((d,i)=>d.addEventListener("click",()=>{show(i);start()}));show(0);start()}
function initCheckout(){
 const form=document.querySelector("#checkoutForm");if(!form)return;
 const p=new URLSearchParams(location.search);
 const productEl=document.querySelector("#product"), qtyEl=document.querySelector("#quantity"), unitEl=document.querySelector("#unitPrice"), amountEl=document.querySelector("#amount");
 const number=document.querySelector("#paymentNumber"), box=document.querySelector("#paymentNumberBox"), label=document.querySelector("#paymentNumberLabel"), codNote=document.querySelector("#codNote"), txn=document.querySelector("#transactionId"), onlineFields=document.querySelector("#onlinePaymentFields"), copy=document.querySelector("#copyPaymentNumber");
 const radios=[...form.querySelectorAll('input[name="payment"]')];
 const basePrice=Math.max(0,Number(p.get("amount")||0));
 const urlQty=Math.max(1,parseInt(p.get("quantity")||"1",10)||1);
 if(p.get("product")){productEl.value=p.get("product");productEl.readOnly=true}
 if(basePrice){unitEl.value=basePrice;qtyEl.value=urlQty}
 const updateAmount=()=>{const q=Math.max(1,parseInt(qtyEl.value||"1",10)||1);qtyEl.value=q;const total=basePrice*q;unitEl.value=basePrice||0;amountEl.value=total||0};
 qtyEl.addEventListener("input",updateAmount);updateAmount();
 const updatePayment=()=>{const method=form.querySelector('input[name="payment"]:checked').value;const online=method!=="cod";box.classList.toggle("hidden",!online);codNote.classList.toggle("hidden",online);onlineFields.classList.toggle("hidden",!online);txn.disabled=!online;txn.required=online;if(online){number.textContent=paymentNumbers[method];label.textContent=currentLang==="bn"?`${method} পেমেন্ট নম্বর`:`${method} payment number`;copy.onclick=()=>copyText(paymentNumbers[method])}else{txn.value=""}};
 radios.forEach(r=>r.addEventListener("change",updatePayment));updatePayment();
 form.addEventListener("submit",e=>{e.preventDefault();updateAmount();const fd=new FormData(form);const data=Object.fromEntries(fd.entries());const method=data.payment;if(method!=="cod"&&!String(data.transaction_id||"").trim()){toast(currentLang==="bn"?"ট্রানজ্যাকশন আইডি দিন।":"Please enter your transaction ID.");return}if(!document.querySelector("#confirmDetails").checked){toast(currentLang==="bn"?"অর্ডার ও পেমেন্ট তথ্য নিশ্চিত করুন।":"Please confirm your order and payment details.");return}data.amount=amountEl.value;data.unit_price=unitEl.value;sessionStorage.setItem("grozOrder",JSON.stringify(data));const msg=["GROZ ORDER REQUEST","Product: "+data.product,"Quantity: "+data.quantity,"Unit Price: ৳"+data.unit_price,"Name: "+data.name,"Phone: "+data.phone,"Email: "+data.email,"Address: "+data.address,"Amount: ৳"+data.amount,"Payment: "+(method==="cod"?"Cash on Delivery":method),"Payment Number: "+(method==="cod"?"N/A":paymentNumbers[method]),"Transaction ID: "+(method==="cod"?"N/A (COD)":String(data.transaction_id).trim()),"","I confirm that the order and payment details above are correct."].join("\n");window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,"_blank")})
}
function getCart(){try{return JSON.parse(localStorage.getItem("grozCart")||"[]")}catch(e){return[]}}
function saveCart(cart){localStorage.setItem("grozCart",JSON.stringify(cart));updateCartCount();}
function updateCartCount(){const count=getCart().reduce((n,i)=>n+(Number(i.quantity)||0),0);document.querySelectorAll("#cartCount").forEach(el=>el.textContent=count)}
function addToCart(product,price,quantity){const cart=getCart();const q=Math.max(1,Math.min(99,Number(quantity)||1));const found=cart.find(i=>i.product===product);if(found)found.quantity=Math.min(99,Number(found.quantity)+q);else cart.push({product,price:Number(price),quantity:q});saveCart(cart);toast(currentLang==="bn"?"কার্টে যোগ হয়েছে":"Added to cart");}
function initCartCount(){updateCartCount()}
function initShopCart(){document.querySelectorAll(".add-cart").forEach(btn=>btn.addEventListener("click",()=>{const card=btn.closest(".product-card"),qty=card?.querySelector(".shop-qty");addToCart(btn.dataset.product,btn.dataset.price,qty?.value||1)}));document.querySelectorAll(".shop-qty").forEach(i=>i.addEventListener("change",()=>{i.value=Math.max(1,Math.min(99,Number(i.value)||1))}))}
function renderCart(){const wrap=document.querySelector("#cartItems");if(!wrap)return;const empty=document.querySelector("#cartEmpty"),content=document.querySelector("#cartContent"),totalEl=document.querySelector("#cartTotal"),cart=getCart();if(!cart.length){empty.classList.remove("hidden");content.classList.add("hidden");return}empty.classList.add("hidden");content.classList.remove("hidden");wrap.innerHTML=cart.map((i,idx)=>`<article class="cart-item"><div class="cart-item-main"><div class="product-icon cart-icon-large">🛒</div><div><h3>${escapeHtml(i.product)}</h3><p class="muted">৳${Number(i.price).toLocaleString()} each</p></div></div><div class="cart-item-controls"><label><span>${typeof currentLang!=="undefined"&&currentLang==="bn"?"পরিমাণ":"Quantity"}</span><input class="cart-qty" data-index="${idx}" type="number" min="1" max="99" value="${i.quantity}"></label><strong>৳${(Number(i.price)*Number(i.quantity)).toLocaleString()}</strong><button class="copy remove-cart" type="button" data-index="${idx}">${typeof currentLang!=="undefined"&&currentLang==="bn"?"সরান":"Remove"}</button><a class="btn" href="checkout.html?product=${encodeURIComponent(i.product)}&amount=${encodeURIComponent(i.price)}&quantity=${encodeURIComponent(i.quantity)}">${typeof currentLang!=="undefined"&&currentLang==="bn"?"Pay & Buy":"Pay & Buy"}</a></div></article>`).join("");totalEl.textContent=cart.reduce((n,i)=>n+Number(i.price)*Number(i.quantity),0).toLocaleString();wrap.querySelectorAll(".cart-qty").forEach(input=>input.addEventListener("change",()=>{const c=getCart(),idx=Number(input.dataset.index);c[idx].quantity=Math.max(1,Math.min(99,Number(input.value)||1));saveCart(c);renderCart()}));wrap.querySelectorAll(".remove-cart").forEach(btn=>btn.addEventListener("click",()=>{const c=getCart();c.splice(Number(btn.dataset.index),1);saveCart(c);renderCart()}));}
function initCart(){initShopCart();renderCart();document.querySelector("#clearCart")?.addEventListener("click",()=>{saveCart([]);renderCart()})}
function initPayment(){const form=document.querySelector("#paymentForm");if(!form)return;const order=JSON.parse(sessionStorage.getItem("grozOrder")||"null");const preview=document.querySelector("#orderPreview");if(!order){preview.innerHTML='<span class="muted">No order details found. Please start from <a href="checkout.html" class="red">Buy Now</a>.</span>'}else{preview.innerHTML=`<b>${escapeHtml(order.product)}</b> × ${escapeHtml(order.quantity)}<br><span class="muted">Customer: ${escapeHtml(order.name)} · Amount: ৳${escapeHtml(order.amount)}</span>`}
 const number=document.querySelector("#paymentNumber"),box=document.querySelector("#paymentNumberBox"),codNote=document.querySelector("#codNote"),txn=document.querySelector("#transactionId"),copy=document.querySelector("#copyPaymentNumber");const radios=[...form.querySelectorAll('input[name="payment"]')];const update=()=>{const method=form.querySelector('input[name="payment"]:checked').value;const online=method!=="cod";box.classList.toggle("hidden",!online);codNote.classList.toggle("hidden",online);txn.disabled=!online;txn.required=online;if(online){number.textContent=paymentNumbers[method];box.querySelector(".muted").textContent=currentLang==="bn"?`${method} পেমেন্ট নম্বর`:`${method} payment number`;copy.onclick=()=>copyText(paymentNumbers[method])}else{txn.value=""}};radios.forEach(r=>r.addEventListener("change",update));update();
 form.addEventListener("submit",e=>{e.preventDefault();if(!order){toast("Please complete Buy Now first.");return}const method=form.querySelector('input[name="payment"]:checked').value;if(method!=="cod"&&!txn.value.trim()){toast("Please enter your transaction ID.");return}if(!document.querySelector("#confirmDetails").checked){toast("Please confirm your payment details.");return}const msg=["GROZ ORDER REQUEST","Product: "+order.product,"Quantity: "+order.quantity,"Name: "+order.name,"Phone: "+order.phone,"Email: "+order.email,"Address: "+order.address,"Amount: ৳"+order.amount,"Payment: "+(method==="cod"?"Cash on Delivery":method),"Payment Number: "+(method==="cod"?"N/A":paymentNumbers[method]),"Transaction ID: "+(method==="cod"?"N/A (COD)":txn.value.trim()),"","I confirm that the order and payment details above are correct."].join("\n");window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,"_blank")})}
function escapeHtml(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

/* GROZ Settings: persistent theme + full UI language switch */
const BN = {
  "Pay & Buy":"পে ও কিনুন","Pay & Buy / Step 1":"পে ও কিনুন / ধাপ ১","Add to Cart":"কার্টে যোগ করুন","Your cart":"আপনার কার্ট","Ready to shop?":"শপিংয়ের জন্য প্রস্তুত?","Open your cart.":"আপনার কার্ট খুলুন।","View Cart 🛒":"কার্ট দেখুন 🛒","Cart 🛒":"কার্ট 🛒","Review your products and quantities before Pay & Buy.":"পে ও কিনুনের আগে আপনার পণ্য ও পরিমাণ দেখুন।","Your cart is empty.":"আপনার কার্ট খালি।","Add products from the Shop to see them here.":"শপ থেকে পণ্য যোগ করলে এখানে দেখা যাবে।","Go to Shop":"শপে যান","Cart summary":"কার্টের সারাংশ","Total":"মোট","Choose Pay & Buy on an item to complete payment and delivery details.":"পেমেন্ট ও ডেলিভারি তথ্য সম্পন্ন করতে একটি পণ্যে পে ও কিনুন নির্বাচন করুন।","Clear Cart":"কার্ট খালি করুন","Remove":"সরান",
  "Settings":"সেটিংস","Theme":"থিম","Dark":"ডার্ক","White":"সাদা","Language":"ভাষা","Your choices are saved automatically.":"আপনার পছন্দগুলো স্বয়ংক্রিয়ভাবে সংরক্ষিত হয়।","Close":"বন্ধ করুন",
  "Home":"হোম","Shop":"শপ","About":"আমাদের সম্পর্কে","Payment":"পেমেন্ট","Contact":"যোগাযোগ","Buy Now":"এখনই কিনুন","Stay connected with GROZ":"GROZ-এর সাথে যুক্ত থাকুন","See what's":"দেখুন কী","next.":"পরেরটি।","Follow GROZ for new arrivals, product drops, offers and behind-the-scenes updates.":"নতুন পণ্য, অফার, প্রোডাক্ট ড্রপ এবং বিশেষ আপডেটের জন্য GROZ-কে ফলো করুন।","Every kind of product, selected for modern life.":"আধুনিক জীবনের জন্য বাছাই করা সব ধরনের পণ্য।","Explore":"ঘুরে দেখুন","WhatsApp:":"হোয়াটসঅ্যাপ:","All rights reserved.":"সর্বস্বত্ব সংরক্ষিত।",
  "GROZ / SIGNATURE MOOD":"GROZ / স্বাক্ষরধর্মী আবহ","Every frame.":"প্রতিটি ফ্রেম।","A different feeling.":"একটি ভিন্ন অনুভূতি।","A visual language built around bold contrast, quiet confidence and a little mystery.":"গাঢ় কনট্রাস্ট, শান্ত আত্মবিশ্বাস আর সামান্য রহস্যে তৈরি এক অনন্য ভিজ্যুয়াল ভাষা।","GROZ / SMALL DETAILS":"GROZ / ছোট ছোট বিবরণ","The smallest details can change the whole look. Discover your next everyday favorite.":"ছোট ছোট বিবরণই পুরো লুক বদলে দিতে পারে। খুঁজে নিন আপনার পরবর্তী দৈনন্দিন পছন্দ।","GROZ / AFTER DARK":"GROZ / রাতের আবহ","Curated with a dark, modern edge — made for people who choose their own style.":"ডার্ক ও আধুনিক আবহে বাছাই করা — যারা নিজের স্টাইল নিজেই বেছে নেন তাদের জন্য।","GROZ / RAW EXPRESSION":"GROZ / স্বতঃস্ফূর্ত প্রকাশ","Different products. Different moods. One place to discover what feels like you.":"ভিন্ন পণ্য। ভিন্ন অনুভূতি। আপনার সঙ্গে মানানসই কিছু খুঁজে নেওয়ার এক ঠিকানা।","GROZ / ART IN THE EVERYDAY":"GROZ / প্রতিদিনের জীবনে শিল্প","A little art, a little attitude — GROZ brings character into everyday shopping.":"একটু শিল্প, একটু আত্মবিশ্বাস — GROZ প্রতিদিনের কেনাকাটায় যোগ করে আলাদা চরিত্র।","GROZ / QUIET CHARACTER":"GROZ / শান্ত স্বাতন্ত্র্য","Distinctive finds for a distinctive routine. Explore the unexpected.":"স্বতন্ত্র রুটিনের জন্য স্বতন্ত্র পছন্দ। অপ্রত্যাশিত কিছু আবিষ্কার করুন।","GROZ / BOLD ENERGY":"GROZ / তীব্র শক্তি","Sharp visuals, useful products and a storefront designed to feel anything but ordinary.":"তীক্ষ্ণ ভিজ্যুয়াল, দরকারি পণ্য এবং সাধারণের চেয়ে আলাদা এক শপিং অভিজ্ঞতা।","GROZ / FIND YOUR SIGNAL":"GROZ / আপনার নিজস্ব সিগন্যাল","Keep scrolling. Keep discovering. Your next GROZ find could be one frame away.":"স্ক্রল করুন। আবিষ্কার করতে থাকুন। আপনার পরবর্তী GROZ পছন্দ হয়তো এক ফ্রেম দূরেই।","5 SEC":"৫ সেকেন্ড",
  "Built for you":"আপনার জন্য তৈরি","Simple shopping.":"সহজ কেনাকাটা।","Sharp experience.":"চমৎকার অভিজ্ঞতা।","Browse dedicated pages, discover your product, complete your customer details, then use the Pay & Buy to finish your order.":"আলাদা পেজে ঘুরে পণ্য বেছে নিন, তথ্য পূরণ করুন এবং নির্দিষ্ট পেমেন্ট পেজে অর্ডার সম্পন্ন করুন।","Curated variety":"বাছাই করা বৈচিত্র্য","Accessories and useful everyday products in one GROZ store.":"এক GROZ স্টোরে অ্যাক্সেসরিজ ও দৈনন্দিন দরকারি পণ্য।","Easy checkout":"সহজ চেকআউট","Customer information stays separate from the payment-confirmation step.":"গ্রাহকের তথ্য পেমেন্ট নিশ্চিতকরণের ধাপ থেকে আলাদা থাকে।","Flexible payment":"নমনীয় পেমেন্ট","bKash, Nagad, Upay, Rocket or Cash on Delivery.":"বিকাশ, নগদ, উপায়, রকেট অথবা ক্যাশ অন ডেলিভারি।","WhatsApp orders":"হোয়াটসঅ্যাপ অর্ডার","Completed orders open directly in WhatsApp with the important details.":"গুরুত্বপূর্ণ তথ্যসহ সম্পন্ন অর্ডার সরাসরি হোয়াটসঅ্যাপে খোলে।","The GROZ point of view":"GROZ-এর দৃষ্টিভঙ্গি","Find something that feels":"এমন কিছু খুঁজুন যা মনে হয়","right.":"আপনারই।","Explore the collection →":"কালেকশন দেখুন →",
  "About GROZ":"GROZ সম্পর্কে","One store.":"একটি স্টোর।","Many possibilities.":"অসংখ্য সম্ভাবনা।","GROZ is built around a simple idea: make discovering useful, stylish and interesting products feel effortless.":"GROZ-এর ধারণা সহজ: দরকারি, স্টাইলিশ ও আকর্ষণীয় পণ্য খুঁজে পাওয়াকে সহজ ও স্বচ্ছন্দ করা।","We sell every kind of product":"আমরা সব ধরনের পণ্য বিক্রি করি","From accessories to useful everyday items, GROZ aims to bring a broad selection under one recognizable brand.":"অ্যাক্সেসরিজ থেকে দৈনন্দিন দরকারি জিনিস—GROZ একটি পরিচিত ব্র্যান্ডের অধীনে বিস্তৃত পণ্য আনতে চায়।","Modern selection":"আধুনিক নির্বাচন","We focus on products that feel practical, current and worth adding to your daily life.":"আমরা এমন পণ্য বেছে নিই যা ব্যবহারিক, আধুনিক এবং দৈনন্দিন জীবনে যোগ করার মতো।","Customer-first checkout":"গ্রাহককেন্দ্রিক চেকআউট","Payment choices, customer details and WhatsApp ordering are organized into a simple flow.":"পেমেন্ট, গ্রাহকের তথ্য এবং হোয়াটসঅ্যাপ অর্ডার একটি সহজ ধাপে সাজানো হয়েছে।","Dropshipping ready":"ড্রপশিপিংয়ের জন্য প্রস্তুত","The storefront is structured so products can be swapped, updated and expanded as your supplier catalog grows.":"আপনার সাপ্লায়ার ক্যাটালগ বাড়ার সঙ্গে পণ্য বদলানো, আপডেট করা ও বাড়ানোর মতো করে স্টোর সাজানো হয়েছে।","Transparent payment":"স্বচ্ছ পেমেন্ট","Online buyers submit their transaction ID for manual confirmation. Wrong amount or invalid transaction details are not treated as confirmed payment.":"অনলাইন ক্রেতারা ম্যানুয়াল যাচাইয়ের জন্য ট্রানজ্যাকশন আইডি দেন। ভুল পরিমাণ বা ভুল তথ্য নিশ্চিত পেমেন্ট হিসেবে ধরা হয় না।","Direct communication":"সরাসরি যোগাযোগ","Once the order form is complete, the customer can send the full order information directly to GROZ WhatsApp.":"অর্ডার ফর্ম পূরণ হলে গ্রাহক সম্পূর্ণ তথ্য সরাসরি GROZ হোয়াটসঅ্যাপে পাঠাতে পারেন।","See what's":"দেখুন কী","Follow GROZ for new arrivals, product drops, offers and behind-the-scenes updates. Tap a red-outlined social icon to open the official page.":"নতুন পণ্য, অফার, প্রোডাক্ট ড্রপ এবং বিশেষ আপডেটের জন্য GROZ-কে ফলো করুন। লাল বর্ডারের সোশ্যাল আইকনে ট্যাপ করে অফিসিয়াল পেজ খুলুন।",
  "Buy now / Step 1":"এখনই কিনুন / ধাপ ১","Your details.":"আপনার তথ্য।","Your order.":"আপনার অর্ডার।","This page is only for your product and delivery details. Payment confirmation is handled separately on the Payment page.":"এই পেজে শুধু পণ্য ও ডেলিভারি তথ্য নেওয়া হয়। পেমেন্ট নিশ্চিতকরণ আলাদা Payment পেজে সম্পন্ন হয়।","Product":"পণ্য","Quantity":"পরিমাণ","Full name":"পুরো নাম","Phone":"ফোন","Email":"ইমেইল","Order amount (৳)":"অর্ডারের পরিমাণ (৳)","Delivery address":"ডেলিভারি ঠিকানা","Next step: choose":"পরের ধাপ: বেছে নিন","on the Pay & Buy. Online payment will require a transaction ID there.":"নির্দিষ্ট Payment পেজে। অনলাইন পেমেন্টে সেখানে ট্রানজ্যাকশন আইডি লাগবে।","Continue to Payment →":"পেমেন্টে যান →",
  "Payment / Step 2":"পেমেন্ট / ধাপ ২","Choose.":"বেছে নিন।","Pay.":"পেমেন্ট করুন।","Confirm.":"নিশ্চিত করুন।","Select a payment app below. The GROZ number appears immediately underneath so you can copy it, send the exact amount, then enter your transaction ID.":"নিচে একটি পেমেন্ট অ্যাপ বেছে নিন। ঠিক নিচে GROZ নম্বর দেখাবে—কপি করে সঠিক পরিমাণ পাঠান, তারপর ট্রানজ্যাকশন আইডি দিন।","Payment method":"পেমেন্ট মাধ্যম","Copy number":"নম্বর কপি করুন","Cash on Delivery selected. No transaction ID is required. Your order will be sent to GROZ WhatsApp as a COD request.":"ক্যাশ অন ডেলিভারি নির্বাচিত। ট্রানজ্যাকশন আইডি লাগবে না। আপনার অর্ডার COD অনুরোধ হিসেবে GROZ হোয়াটসঅ্যাপে পাঠানো হবে।","Payment confirmation":"পেমেন্ট নিশ্চিতকরণ","Transaction ID":"ট্রানজ্যাকশন আইডি","Please send the":"দয়া করে পাঠান","exact order amount":"সঠিক অর্ডারের পরিমাণ",". If the amount or transaction ID is wrong, the payment cannot be treated as confirmed.":"। পরিমাণ বা ট্রানজ্যাকশন আইডি ভুল হলে পেমেন্ট নিশ্চিত হিসেবে ধরা হবে না।","I confirm my payment details are correct.":"আমি নিশ্চিত করছি যে আমার পেমেন্টের তথ্য সঠিক।","Send Order to WhatsApp →":"হোয়াটসঅ্যাপে অর্ডার পাঠান →",
  "The collection":"কালেকশন","Shop":"শপ","GROZ.":"GROZ।","Demo products are ready for your catalog. Replace names, prices and descriptions with your live dropshipping products.":"ডেমো পণ্যগুলো আপনার ক্যাটালগের জন্য প্রস্তুত। আপনার লাইভ ড্রপশিপিং পণ্য দিয়ে নাম, দাম ও বর্ণনা পরিবর্তন করুন।","Buy now":"এখনই কিনুন","TRENDING":"ট্রেন্ডিং","ACCESSORY":"অ্যাক্সেসরিজ","Minimal Smart Watch":"মিনিমাল স্মার্ট ওয়াচ","Modern everyday wearable with a clean profile.":"পরিষ্কার ডিজাইনের আধুনিক দৈনন্দিন পরিধেয় পণ্য।","NEW":"নতুন","STYLE":"স্টাইল","Urban Frame":"আরবান ফ্রেম","A sleek accessory made for daily looks.":"দৈনন্দিন লুকের জন্য স্টাইলিশ অ্যাক্সেসরিজ।","BESTSELLER":"বেস্টসেলার","Wireless Audio Pro":"ওয়্যারলেস অডিও প্রো","Compact wireless listening for work and travel.":"কাজ ও ভ্রমণের জন্য কমপ্যাক্ট ওয়্যারলেস অডিও।","DAILY":"দৈনন্দিন","Utility Crossbody":"ইউটিলিটি ক্রসবডি","Compact carry with a modern streetwear feel.":"আধুনিক স্ট্রিটওয়্যার স্টাইলে কমপ্যাক্ট ব্যাগ।","Classic Steel Ring":"ক্লাসিক স্টিল রিং","Minimal finish designed for everyday wear.":"দৈনন্দিন ব্যবহারের জন্য মিনিমাল ফিনিশ।","UTILITY":"ইউটিলিটি","Fast Charge Kit":"ফাস্ট চার্জ কিট","A practical charging accessory for your setup.":"আপনার সেটআপের জন্য ব্যবহারিক চার্জিং অ্যাক্সেসরিজ।",
  "Contact GROZ":"GROZ-এ যোগাযোগ করুন","Let's talk":"চলুন কথা বলি","commerce.":"ব্যবসা নিয়ে।","For product questions, order help or business inquiries, use the details below.":"পণ্য, অর্ডার সহায়তা বা ব্যবসায়িক প্রশ্নের জন্য নিচের তথ্য ব্যবহার করুন।","Address":"ঠিকানা","Maijdee Court, Noakhali, Bangladesh":"মাইজদী কোর্ট, নোয়াখালী, বাংলাদেশ","Chat on WhatsApp":"হোয়াটসঅ্যাপে কথা বলুন","Email":"ইমেইল",
  "Dark theme":"ডার্ক থিম","White theme":"সাদা থিম",
  "Pay & Buy Now / Step 1":"পে ও এখনই কিনুন / ধাপ ১","Pay & Buy Now":"পে ও এখনই কিনুন","Complete your order.":"আপনার অর্ডার সম্পন্ন করুন।","Choose your payment method first, then enter your product and delivery details below. The order amount is calculated automatically from unit price × quantity.":"প্রথমে পেমেন্ট মাধ্যম বেছে নিন, তারপর নিচে পণ্য ও ডেলিভারি তথ্য দিন। ইউনিট মূল্য × পরিমাণ অনুযায়ী অর্ডারের মোট টাকা স্বয়ংক্রিয়ভাবে হিসাব হবে।","Choose payment method":"পেমেন্ট মাধ্যম বেছে নিন","Cash on Delivery":"ক্যাশ অন ডেলিভারি","Cash on Delivery selected. No transaction ID is required.":"ক্যাশ অন ডেলিভারি নির্বাচিত। ট্রানজ্যাকশন আইডি প্রয়োজন নেই।","Enter transaction ID after payment":"পেমেন্টের পর ট্রানজ্যাকশন আইডি দিন","Send the exact order amount. Wrong amount or transaction ID will not be confirmed.":"সঠিক অর্ডারের পরিমাণ পাঠান। ভুল পরিমাণ বা ট্রানজ্যাকশন আইডি নিশ্চিত করা হবে না।","Your order":"আপনার অর্ডার","Order details":"অর্ডারের তথ্য","Unit price (৳)":"ইউনিট মূল্য (৳)","Order amount = unit price × quantity. The total updates automatically when you change quantity.":"অর্ডারের পরিমাণ = ইউনিট মূল্য × পরিমাণ। পরিমাণ পরিবর্তন করলে মোট টাকা স্বয়ংক্রিয়ভাবে আপডেট হবে।","I confirm that my order and payment details are correct.":"আমি নিশ্চিত করছি যে আমার অর্ডার ও পেমেন্টের তথ্য সঠিক।","Place Order on WhatsApp →":"হোয়াটসঅ্যাপে অর্ডার পাঠান →"
};

const ATTR_BN={"Settings":"সেটিংস","Close":"বন্ধ করুন","Product name":"পণ্যের নাম","Your name":"আপনার নাম","01XXXXXXXXX":"০১XXXXXXXXX","you@example.com":"আপনার@ইমেইল.কম","House / Road / Area / District":"বাড়ি / রোড / এলাকা / জেলা","Required for online payment":"অনলাইন পেমেন্টের জন্য প্রয়োজনীয়"};
let currentLang="en";
let originalTextNodes=new WeakMap();
let originalAttrs=new WeakMap();
function normalizeText(s){return s.replace(/\s+/g,' ').trim()}
function translatePage(lang){
 currentLang=lang;
 document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;el.textContent=lang==='bn'?(BN[key]||key):key});
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
 let n;while(n=walker.nextNode()){
   if(!n.nodeValue.trim())continue;
   if(!originalTextNodes.has(n))originalTextNodes.set(n,n.nodeValue);
   const en=originalTextNodes.get(n), key=normalizeText(en);
   if(!key)continue;
   const translated=lang==='bn'?(BN[key]||null):key;
   if(translated){const lead=en.match(/^\s*/)?.[0]||'',trail=en.match(/\s*$/)?.[0]||'';n.nodeValue=lead+translated+trail}
 }
 document.querySelectorAll('input,textarea,select,button,a,[title],[aria-label]').forEach(el=>{
   ['placeholder','title','aria-label'].forEach(attr=>{if(!el.hasAttribute(attr))return;if(!originalAttrs.has(el))originalAttrs.set(el,{});const store=originalAttrs.get(el);if(store[attr]===undefined)store[attr]=el.getAttribute(attr);const key=store[attr];el.setAttribute(attr,lang==='bn'?(ATTR_BN[key]||BN[key]||key):key)});
 });
 const payBox=document.querySelector("#paymentNumberBox"), payForm=document.querySelector("#paymentForm");
 if(payBox&&payForm){const selected=payForm.querySelector('input[name="payment"]:checked');if(selected&&selected.value!=="cod"){const m=selected.value;const muted=payBox.querySelector(".muted");if(muted)muted.textContent=lang==="bn"?`${m} পেমেন্ট নম্বর`:`${m} payment number`;}}
 const preview=document.querySelector("#orderPreview");
 if(preview){try{const order=JSON.parse(sessionStorage.getItem("grozOrder")||"null");if(order){preview.innerHTML=lang==="bn"?`<b>${escapeHtml(order.product)}</b> × ${escapeHtml(order.quantity)}<br><span class="muted">ক্রেতা: ${escapeHtml(order.name)} · পরিমাণ: ৳${escapeHtml(order.amount)}</span>`:`<b>${escapeHtml(order.product)}</b> × ${escapeHtml(order.quantity)}<br><span class="muted">Customer: ${escapeHtml(order.name)} · Amount: ৳${escapeHtml(order.amount)}</span>`;}}catch(e){}}
 document.documentElement.lang=lang==='bn'?'bn':'en';
 localStorage.setItem('grozLanguage',lang);
 document.querySelectorAll('[data-lang-choice]').forEach(b=>b.classList.toggle('active',b.dataset.langChoice===lang));
}
function applyTheme(theme){
 if(theme!=='dark'&&theme!=='white')theme='dark';
 document.body.classList.remove('theme-white');
 if(theme==='white')document.body.classList.add('theme-white');
 localStorage.setItem('grozTheme',theme);
 document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===theme));
}
function initSettings(){
 const btn=document.querySelector('#settingsBtn'),panel=document.querySelector('#settingsPanel'),close=document.querySelector('#settingsClose');if(!btn||!panel)return;
 const toggle=open=>{panel.classList.toggle('open',open);panel.setAttribute('aria-hidden',String(!open))};
 btn.addEventListener('click',e=>{e.stopPropagation();toggle(!panel.classList.contains('open'))});close?.addEventListener('click',()=>toggle(false));document.addEventListener('click',e=>{if(!panel.contains(e.target)&&e.target!==btn)toggle(false)});
 document.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>applyTheme(b.dataset.themeChoice)));
 document.querySelectorAll('[data-lang-choice]').forEach(b=>b.addEventListener('click',()=>translatePage(b.dataset.langChoice)));
 applyTheme(localStorage.getItem('grozTheme')||'dark');translatePage(localStorage.getItem('grozLanguage')||'en');
}

// Run after the original GROZ page initializers so all settings controls are ready.
document.addEventListener('DOMContentLoaded',initSettings);
